#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cnWorld
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WorldDB")]
	public partial class dbWorldDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertproducto(enWorld.producto instance);
    partial void Updateproducto(enWorld.producto instance);
    partial void Deleteproducto(enWorld.producto instance);
    partial void InsertlineaSolicitud(enWorld.lineaSolicitud instance);
    partial void UpdatelineaSolicitud(enWorld.lineaSolicitud instance);
    partial void DeletelineaSolicitud(enWorld.lineaSolicitud instance);
    partial void InsertCOUNTRY(enWorld.COUNTRY instance);
    partial void UpdateCOUNTRY(enWorld.COUNTRY instance);
    partial void DeleteCOUNTRY(enWorld.COUNTRY instance);
    partial void InsertPERSON(enWorld.PERSON instance);
    partial void UpdatePERSON(enWorld.PERSON instance);
    partial void DeletePERSON(enWorld.PERSON instance);
    #endregion
		
		public dbWorldDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["WorldDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbWorldDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWorldDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWorldDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbWorldDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<enWorld.producto> productos
		{
			get
			{
				return this.GetTable<enWorld.producto>();
			}
		}
		
		public System.Data.Linq.Table<enWorld.lineaSolicitud> lineaSolicituds
		{
			get
			{
				return this.GetTable<enWorld.lineaSolicitud>();
			}
		}
		
		public System.Data.Linq.Table<enWorld.COUNTRY> COUNTRies
		{
			get
			{
				return this.GetTable<enWorld.COUNTRY>();
			}
		}
		
		public System.Data.Linq.Table<enWorld.PERSON> PERSONs
		{
			get
			{
				return this.GetTable<enWorld.PERSON>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SELECT_PIECE")]
		public ISingleResult<enWorld.SELECT_PIECEResult> SELECT_PIECE([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,0)")] System.Nullable<decimal> n_page)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), n_page);
			return ((ISingleResult<enWorld.SELECT_PIECEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SELECT_PIECE_PERSON")]
		public ISingleResult<enWorld.SELECT_PIECE_PERSONResult> SELECT_PIECE_PERSON([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,0)")] System.Nullable<decimal> n_page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,0)")] System.Nullable<decimal> page_size)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), n_page, page_size);
			return ((ISingleResult<enWorld.SELECT_PIECE_PERSONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.COUNTRY_INFO")]
		public ISingleResult<enWorld.COUNTRY_INFOResult> COUNTRY_INFO([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> size)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), page, size);
			return ((ISingleResult<enWorld.COUNTRY_INFOResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PEOPLE_YEAR_COUNTRY")]
		public ISingleResult<enWorld.PEOPLE_YEAR_COUNTRYResult> PEOPLE_YEAR_COUNTRY([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,0)")] System.Nullable<decimal> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> size)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, page, size);
			return ((ISingleResult<enWorld.PEOPLE_YEAR_COUNTRYResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PEOPLE_YEAR_ALL_COUNTRIES")]
		public ISingleResult<enWorld.PEOPLE_YEAR_ALL_COUNTRIESResult> PEOPLE_YEAR_ALL_COUNTRIES([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> page, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> size)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), page, size);
			return ((ISingleResult<enWorld.PEOPLE_YEAR_ALL_COUNTRIESResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GENERATE_PEOPLE_fast")]
		public int GENERATE_PEOPLE_fast([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,0)")] System.Nullable<decimal> countries, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,0)")] System.Nullable<decimal> population)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), countries, population);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_PAGE_COUNTRY")]
		public ISingleResult<enWorld.GET_PAGE_COUNTRYResult> GET_PAGE_COUNTRY([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), page);
			return ((ISingleResult<enWorld.GET_PAGE_COUNTRYResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_PAGE_PERSON")]
		public ISingleResult<enWorld.GET_PAGE_PERSONResult> GET_PAGE_PERSON([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> page)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), page);
			return ((ISingleResult<enWorld.GET_PAGE_PERSONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QUERY_II")]
		public ISingleResult<enWorld.QUERY_IIResult> QUERY_II()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<enWorld.QUERY_IIResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.MAX_DATES")]
		public ISingleResult<enWorld.MAX_DATESResult> MAX_DATES()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<enWorld.MAX_DATESResult>)(result.ReturnValue));
		}
	}
}
namespace enWorld
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.producto")]
	public partial class producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _noProducto;
		
		private string _nbrProducto;
		
		private EntitySet<lineaSolicitud> _lineaSolicituds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnoProductoChanging(decimal value);
    partial void OnnoProductoChanged();
    partial void OnnbrProductoChanging(string value);
    partial void OnnbrProductoChanged();
    #endregion
		
		public producto()
		{
			this._lineaSolicituds = new EntitySet<lineaSolicitud>(new Action<lineaSolicitud>(this.attach_lineaSolicituds), new Action<lineaSolicitud>(this.detach_lineaSolicituds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noProducto", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
		public decimal noProducto
		{
			get
			{
				return this._noProducto;
			}
			set
			{
				if ((this._noProducto != value))
				{
					this.OnnoProductoChanging(value);
					this.SendPropertyChanging();
					this._noProducto = value;
					this.SendPropertyChanged("noProducto");
					this.OnnoProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nbrProducto", DbType="VarChar(50)")]
		public string nbrProducto
		{
			get
			{
				return this._nbrProducto;
			}
			set
			{
				if ((this._nbrProducto != value))
				{
					this.OnnbrProductoChanging(value);
					this.SendPropertyChanging();
					this._nbrProducto = value;
					this.SendPropertyChanged("nbrProducto");
					this.OnnbrProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_lineaSolicitud", Storage="_lineaSolicituds", ThisKey="noProducto", OtherKey="noProducto")]
		public EntitySet<lineaSolicitud> lineaSolicituds
		{
			get
			{
				return this._lineaSolicituds;
			}
			set
			{
				this._lineaSolicituds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_lineaSolicituds(lineaSolicitud entity)
		{
			this.SendPropertyChanging();
			entity.producto = this;
		}
		
		private void detach_lineaSolicituds(lineaSolicitud entity)
		{
			this.SendPropertyChanging();
			entity.producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lineaSolicitud")]
	public partial class lineaSolicitud : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _noSolicitud;
		
		private decimal _noProducto;
		
		private System.Nullable<decimal> _cantidad;
		
		private System.Nullable<decimal> _monto;
		
		private EntityRef<producto> _producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnoSolicitudChanging(decimal value);
    partial void OnnoSolicitudChanged();
    partial void OnnoProductoChanging(decimal value);
    partial void OnnoProductoChanged();
    partial void OncantidadChanging(System.Nullable<decimal> value);
    partial void OncantidadChanged();
    partial void OnmontoChanging(System.Nullable<decimal> value);
    partial void OnmontoChanged();
    #endregion
		
		public lineaSolicitud()
		{
			this._producto = default(EntityRef<producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noSolicitud", DbType="Decimal(5,0) NOT NULL", IsPrimaryKey=true)]
		public decimal noSolicitud
		{
			get
			{
				return this._noSolicitud;
			}
			set
			{
				if ((this._noSolicitud != value))
				{
					this.OnnoSolicitudChanging(value);
					this.SendPropertyChanging();
					this._noSolicitud = value;
					this.SendPropertyChanged("noSolicitud");
					this.OnnoSolicitudChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noProducto", DbType="Decimal(3,0) NOT NULL", IsPrimaryKey=true)]
		public decimal noProducto
		{
			get
			{
				return this._noProducto;
			}
			set
			{
				if ((this._noProducto != value))
				{
					if (this._producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnnoProductoChanging(value);
					this.SendPropertyChanging();
					this._noProducto = value;
					this.SendPropertyChanged("noProducto");
					this.OnnoProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto", DbType="Decimal(17,2)")]
		public System.Nullable<decimal> monto
		{
			get
			{
				return this._monto;
			}
			set
			{
				if ((this._monto != value))
				{
					this.OnmontoChanging(value);
					this.SendPropertyChanging();
					this._monto = value;
					this.SendPropertyChanged("monto");
					this.OnmontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="producto_lineaSolicitud", Storage="_producto", ThisKey="noProducto", OtherKey="noProducto", IsForeignKey=true)]
		public producto producto
		{
			get
			{
				return this._producto.Entity;
			}
			set
			{
				producto previousValue = this._producto.Entity;
				if (((previousValue != value) 
							|| (this._producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._producto.Entity = null;
						previousValue.lineaSolicituds.Remove(this);
					}
					this._producto.Entity = value;
					if ((value != null))
					{
						value.lineaSolicituds.Add(this);
						this._noProducto = value.noProducto;
					}
					else
					{
						this._noProducto = default(decimal);
					}
					this.SendPropertyChanged("producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COUNTRY")]
	public partial class COUNTRY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _COUNTRYID;
		
		private string _COUNTRYNAME;
		
		private decimal _AREA;
		
		private decimal _POPULATION;
		
		private System.Guid _FILEID;
		
		private System.Data.Linq.Binary _FLAG;
		
		private System.Data.Linq.Binary _ANTHEM;
		
		private System.Nullable<decimal> _PRESIDENT;
		
		private EntitySet<PERSON> _PERSONs;
		
		private EntitySet<PERSON> _PERSONs1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOUNTRYIDChanging(decimal value);
    partial void OnCOUNTRYIDChanged();
    partial void OnCOUNTRYNAMEChanging(string value);
    partial void OnCOUNTRYNAMEChanged();
    partial void OnAREAChanging(decimal value);
    partial void OnAREAChanged();
    partial void OnPOPULATIONChanging(decimal value);
    partial void OnPOPULATIONChanged();
    partial void OnFILEIDChanging(System.Guid value);
    partial void OnFILEIDChanged();
    partial void OnFLAGChanging(System.Data.Linq.Binary value);
    partial void OnFLAGChanged();
    partial void OnANTHEMChanging(System.Data.Linq.Binary value);
    partial void OnANTHEMChanged();
    partial void OnPRESIDENTChanging(System.Nullable<decimal> value);
    partial void OnPRESIDENTChanged();
    #endregion
		
		public COUNTRY()
		{
			this._PERSONs = new EntitySet<PERSON>(new Action<PERSON>(this.attach_PERSONs), new Action<PERSON>(this.detach_PERSONs));
			this._PERSONs1 = new EntitySet<PERSON>(new Action<PERSON>(this.attach_PERSONs1), new Action<PERSON>(this.detach_PERSONs1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYID", DbType="Decimal(10,0) NOT NULL", IsPrimaryKey=true)]
		public decimal COUNTRYID
		{
			get
			{
				return this._COUNTRYID;
			}
			set
			{
				if ((this._COUNTRYID != value))
				{
					this.OnCOUNTRYIDChanging(value);
					this.SendPropertyChanging();
					this._COUNTRYID = value;
					this.SendPropertyChanged("COUNTRYID");
					this.OnCOUNTRYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this.OnCOUNTRYNAMEChanging(value);
					this.SendPropertyChanging();
					this._COUNTRYNAME = value;
					this.SendPropertyChanged("COUNTRYNAME");
					this.OnCOUNTRYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA", DbType="Decimal(15,5) NOT NULL")]
		public decimal AREA
		{
			get
			{
				return this._AREA;
			}
			set
			{
				if ((this._AREA != value))
				{
					this.OnAREAChanging(value);
					this.SendPropertyChanging();
					this._AREA = value;
					this.SendPropertyChanged("AREA");
					this.OnAREAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POPULATION", DbType="Decimal(15,5) NOT NULL")]
		public decimal POPULATION
		{
			get
			{
				return this._POPULATION;
			}
			set
			{
				if ((this._POPULATION != value))
				{
					this.OnPOPULATIONChanging(value);
					this.SendPropertyChanging();
					this._POPULATION = value;
					this.SendPropertyChanged("POPULATION");
					this.OnPOPULATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILEID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid FILEID
		{
			get
			{
				return this._FILEID;
			}
			set
			{
				if ((this._FILEID != value))
				{
					this.OnFILEIDChanging(value);
					this.SendPropertyChanging();
					this._FILEID = value;
					this.SendPropertyChanged("FILEID");
					this.OnFILEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FLAG
		{
			get
			{
				return this._FLAG;
			}
			set
			{
				if ((this._FLAG != value))
				{
					this.OnFLAGChanging(value);
					this.SendPropertyChanging();
					this._FLAG = value;
					this.SendPropertyChanged("FLAG");
					this.OnFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANTHEM", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ANTHEM
		{
			get
			{
				return this._ANTHEM;
			}
			set
			{
				if ((this._ANTHEM != value))
				{
					this.OnANTHEMChanging(value);
					this.SendPropertyChanging();
					this._ANTHEM = value;
					this.SendPropertyChanged("ANTHEM");
					this.OnANTHEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRESIDENT", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> PRESIDENT
		{
			get
			{
				return this._PRESIDENT;
			}
			set
			{
				if ((this._PRESIDENT != value))
				{
					this.OnPRESIDENTChanging(value);
					this.SendPropertyChanging();
					this._PRESIDENT = value;
					this.SendPropertyChanged("PRESIDENT");
					this.OnPRESIDENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COUNTRY_PERSON", Storage="_PERSONs", ThisKey="COUNTRYID", OtherKey="BIRTH_COUNTRY")]
		public EntitySet<PERSON> PERSONs
		{
			get
			{
				return this._PERSONs;
			}
			set
			{
				this._PERSONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COUNTRY_PERSON1", Storage="_PERSONs1", ThisKey="COUNTRYID", OtherKey="RESIDENCE_COUNTRY")]
		public EntitySet<PERSON> PERSONs1
		{
			get
			{
				return this._PERSONs1;
			}
			set
			{
				this._PERSONs1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PERSONs(PERSON entity)
		{
			this.SendPropertyChanging();
			entity.COUNTRY = this;
		}
		
		private void detach_PERSONs(PERSON entity)
		{
			this.SendPropertyChanging();
			entity.COUNTRY = null;
		}
		
		private void attach_PERSONs1(PERSON entity)
		{
			this.SendPropertyChanging();
			entity.COUNTRY1 = this;
		}
		
		private void detach_PERSONs1(PERSON entity)
		{
			this.SendPropertyChanging();
			entity.COUNTRY1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERSON")]
	public partial class PERSON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _IDENTIFICATION;
		
		private string _NAME;
		
		private decimal _BIRTH_COUNTRY;
		
		private decimal _RESIDENCE_COUNTRY;
		
		private System.DateTime _BIRTH_DATE;
		
		private string _EMAIL;
		
		private System.Guid _FILEID;
		
		private System.Data.Linq.Binary _PHOTO;
		
		private string _VIDEO;
		
		private EntityRef<COUNTRY> _COUNTRY;
		
		private EntityRef<COUNTRY> _COUNTRY1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDENTIFICATIONChanging(decimal value);
    partial void OnIDENTIFICATIONChanged();
    partial void OnNAMEChanging(string value);
    partial void OnNAMEChanged();
    partial void OnBIRTH_COUNTRYChanging(decimal value);
    partial void OnBIRTH_COUNTRYChanged();
    partial void OnRESIDENCE_COUNTRYChanging(decimal value);
    partial void OnRESIDENCE_COUNTRYChanged();
    partial void OnBIRTH_DATEChanging(System.DateTime value);
    partial void OnBIRTH_DATEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnFILEIDChanging(System.Guid value);
    partial void OnFILEIDChanged();
    partial void OnPHOTOChanging(System.Data.Linq.Binary value);
    partial void OnPHOTOChanged();
    partial void OnVIDEOChanging(string value);
    partial void OnVIDEOChanged();
    #endregion
		
		public PERSON()
		{
			this._COUNTRY = default(EntityRef<COUNTRY>);
			this._COUNTRY1 = default(EntityRef<COUNTRY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFICATION", DbType="Decimal(10,0) NOT NULL", IsPrimaryKey=true)]
		public decimal IDENTIFICATION
		{
			get
			{
				return this._IDENTIFICATION;
			}
			set
			{
				if ((this._IDENTIFICATION != value))
				{
					this.OnIDENTIFICATIONChanging(value);
					this.SendPropertyChanging();
					this._IDENTIFICATION = value;
					this.SendPropertyChanged("IDENTIFICATION");
					this.OnIDENTIFICATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this.OnNAMEChanging(value);
					this.SendPropertyChanging();
					this._NAME = value;
					this.SendPropertyChanged("NAME");
					this.OnNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_COUNTRY", DbType="Decimal(10,0) NOT NULL")]
		public decimal BIRTH_COUNTRY
		{
			get
			{
				return this._BIRTH_COUNTRY;
			}
			set
			{
				if ((this._BIRTH_COUNTRY != value))
				{
					if (this._COUNTRY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBIRTH_COUNTRYChanging(value);
					this.SendPropertyChanging();
					this._BIRTH_COUNTRY = value;
					this.SendPropertyChanged("BIRTH_COUNTRY");
					this.OnBIRTH_COUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIDENCE_COUNTRY", DbType="Decimal(10,0) NOT NULL")]
		public decimal RESIDENCE_COUNTRY
		{
			get
			{
				return this._RESIDENCE_COUNTRY;
			}
			set
			{
				if ((this._RESIDENCE_COUNTRY != value))
				{
					if (this._COUNTRY1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRESIDENCE_COUNTRYChanging(value);
					this.SendPropertyChanging();
					this._RESIDENCE_COUNTRY = value;
					this.SendPropertyChanged("RESIDENCE_COUNTRY");
					this.OnRESIDENCE_COUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="Date NOT NULL")]
		public System.DateTime BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this.OnBIRTH_DATEChanging(value);
					this.SendPropertyChanging();
					this._BIRTH_DATE = value;
					this.SendPropertyChanged("BIRTH_DATE");
					this.OnBIRTH_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FILEID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid FILEID
		{
			get
			{
				return this._FILEID;
			}
			set
			{
				if ((this._FILEID != value))
				{
					this.OnFILEIDChanging(value);
					this.SendPropertyChanging();
					this._FILEID = value;
					this.SendPropertyChanged("FILEID");
					this.OnFILEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHOTO", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary PHOTO
		{
			get
			{
				return this._PHOTO;
			}
			set
			{
				if ((this._PHOTO != value))
				{
					this.OnPHOTOChanging(value);
					this.SendPropertyChanging();
					this._PHOTO = value;
					this.SendPropertyChanged("PHOTO");
					this.OnPHOTOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIDEO", DbType="VarChar(300) NOT NULL", CanBeNull=false)]
		public string VIDEO
		{
			get
			{
				return this._VIDEO;
			}
			set
			{
				if ((this._VIDEO != value))
				{
					this.OnVIDEOChanging(value);
					this.SendPropertyChanging();
					this._VIDEO = value;
					this.SendPropertyChanged("VIDEO");
					this.OnVIDEOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COUNTRY_PERSON", Storage="_COUNTRY", ThisKey="BIRTH_COUNTRY", OtherKey="COUNTRYID", IsForeignKey=true)]
		public COUNTRY COUNTRY
		{
			get
			{
				return this._COUNTRY.Entity;
			}
			set
			{
				COUNTRY previousValue = this._COUNTRY.Entity;
				if (((previousValue != value) 
							|| (this._COUNTRY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COUNTRY.Entity = null;
						previousValue.PERSONs.Remove(this);
					}
					this._COUNTRY.Entity = value;
					if ((value != null))
					{
						value.PERSONs.Add(this);
						this._BIRTH_COUNTRY = value.COUNTRYID;
					}
					else
					{
						this._BIRTH_COUNTRY = default(decimal);
					}
					this.SendPropertyChanged("COUNTRY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="COUNTRY_PERSON1", Storage="_COUNTRY1", ThisKey="RESIDENCE_COUNTRY", OtherKey="COUNTRYID", IsForeignKey=true)]
		public COUNTRY COUNTRY1
		{
			get
			{
				return this._COUNTRY1.Entity;
			}
			set
			{
				COUNTRY previousValue = this._COUNTRY1.Entity;
				if (((previousValue != value) 
							|| (this._COUNTRY1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._COUNTRY1.Entity = null;
						previousValue.PERSONs1.Remove(this);
					}
					this._COUNTRY1.Entity = value;
					if ((value != null))
					{
						value.PERSONs1.Add(this);
						this._RESIDENCE_COUNTRY = value.COUNTRYID;
					}
					else
					{
						this._RESIDENCE_COUNTRY = default(decimal);
					}
					this.SendPropertyChanged("COUNTRY1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class SELECT_PIECEResult
	{
		
		private decimal _COUNTRYID;
		
		private string _COUNTRYNAME;
		
		private decimal _AREA;
		
		private decimal _POPULATION;
		
		private decimal? _PRESIDENT;
		
		public SELECT_PIECEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYID", DbType="Decimal(10,0) NOT NULL")]
		public decimal COUNTRYID
		{
			get
			{
				return this._COUNTRYID;
			}
			set
			{
				if ((this._COUNTRYID != value))
				{
					this._COUNTRYID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this._COUNTRYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA", DbType="Decimal(15,5) NOT NULL")]
		public decimal AREA
		{
			get
			{
				return this._AREA;
			}
			set
			{
				if ((this._AREA != value))
				{
					this._AREA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POPULATION", DbType="Decimal(15,5) NOT NULL")]
		public decimal POPULATION
		{
			get
			{
				return this._POPULATION;
			}
			set
			{
				if ((this._POPULATION != value))
				{
					this._POPULATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRESIDENT", DbType="Decimal(10,0) NOT NULL")]
		public decimal? PRESIDENT
		{
			get
			{
				return this._PRESIDENT;
			}
			set
			{
				if ((this._PRESIDENT != value))
				{
					this._PRESIDENT = value;
				}
			}
		}
	}
	
	public partial class SELECT_PIECE_PERSONResult
	{
		
		private decimal _BIRTH_COUNTRY;
		
		private System.DateTime _BIRTH_DATE;
		
		private string _BNAME;
		
		private string _EMAIL;
		
		private decimal _IDENTIFICATION;
		
		private string _NAME;
		
		private decimal _RESIDENCE_COUNTRY;
		
		private string _RNAME;
		
		public SELECT_PIECE_PERSONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_COUNTRY", DbType="Decimal(10,0) NOT NULL")]
		public decimal BIRTH_COUNTRY
		{
			get
			{
				return this._BIRTH_COUNTRY;
			}
			set
			{
				if ((this._BIRTH_COUNTRY != value))
				{
					this._BIRTH_COUNTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIRTH_DATE", DbType="Date NOT NULL")]
		public System.DateTime BIRTH_DATE
		{
			get
			{
				return this._BIRTH_DATE;
			}
			set
			{
				if ((this._BIRTH_DATE != value))
				{
					this._BIRTH_DATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BNAME
		{
			get
			{
				return this._BNAME;
			}
			set
			{
				if ((this._BNAME != value))
				{
					this._BNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this._EMAIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDENTIFICATION", DbType="Decimal(10,0) NOT NULL")]
		public decimal IDENTIFICATION
		{
			get
			{
				return this._IDENTIFICATION;
			}
			set
			{
				if ((this._IDENTIFICATION != value))
				{
					this._IDENTIFICATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIDENCE_COUNTRY", DbType="Decimal(10,0) NOT NULL")]
		public decimal RESIDENCE_COUNTRY
		{
			get
			{
				return this._RESIDENCE_COUNTRY;
			}
			set
			{
				if ((this._RESIDENCE_COUNTRY != value))
				{
					this._RESIDENCE_COUNTRY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RNAME
		{
			get
			{
				return this._RNAME;
			}
			set
			{
				if ((this._RNAME != value))
				{
					this._RNAME = value;
				}
			}
		}
	}
	
	public partial class COUNTRY_INFOResult
	{
		
		private decimal _COUNTRYID;
		
		private string _COUNTRYNAME;
		
		private System.Nullable<int> _AGE;
		
		private System.Nullable<int> _POPULATION;
		
		public COUNTRY_INFOResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYID", DbType="Decimal(10,0) NOT NULL")]
		public decimal COUNTRYID
		{
			get
			{
				return this._COUNTRYID;
			}
			set
			{
				if ((this._COUNTRYID != value))
				{
					this._COUNTRYID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this._COUNTRYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AGE", DbType="Int")]
		public System.Nullable<int> AGE
		{
			get
			{
				return this._AGE;
			}
			set
			{
				if ((this._AGE != value))
				{
					this._AGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POPULATION", DbType="Int")]
		public System.Nullable<int> POPULATION
		{
			get
			{
				return this._POPULATION;
			}
			set
			{
				if ((this._POPULATION != value))
				{
					this._POPULATION = value;
				}
			}
		}
	}
	
	public partial class PEOPLE_YEAR_COUNTRYResult
	{
		
		private System.Nullable<int> _YEAR;
		
		private System.Nullable<int> _BORN;
		
		public PEOPLE_YEAR_COUNTRYResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Int")]
		public System.Nullable<int> YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this._YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORN", DbType="Int")]
		public System.Nullable<int> BORN
		{
			get
			{
				return this._BORN;
			}
			set
			{
				if ((this._BORN != value))
				{
					this._BORN = value;
				}
			}
		}
	}
	
	public partial class PEOPLE_YEAR_ALL_COUNTRIESResult
	{
		
		private System.Nullable<int> _YEAR;
		
		private System.Nullable<int> _BORN;
		
		public PEOPLE_YEAR_ALL_COUNTRIESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Int")]
		public System.Nullable<int> YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this._YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BORN", DbType="Int")]
		public System.Nullable<int> BORN
		{
			get
			{
				return this._BORN;
			}
			set
			{
				if ((this._BORN != value))
				{
					this._BORN = value;
				}
			}
		}
	}
	
	public partial class GET_PAGE_COUNTRYResult
	{
		
		private System.Nullable<double> _N;
		
		public GET_PAGE_COUNTRYResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N", DbType="Float")]
		public System.Nullable<double> N
		{
			get
			{
				return this._N;
			}
			set
			{
				if ((this._N != value))
				{
					this._N = value;
				}
			}
		}
	}
	
	public partial class GET_PAGE_PERSONResult
	{
		
		private System.Nullable<double> _N;
		
		public GET_PAGE_PERSONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_N", DbType="Float")]
		public System.Nullable<double> N
		{
			get
			{
				return this._N;
			}
			set
			{
				if ((this._N != value))
				{
					this._N = value;
				}
			}
		}
	}
	
	public partial class QUERY_IIResult
	{
		
		private System.Nullable<decimal> _COUNTRYID;
		
		private string _COUNTRYNAME;
		
		private System.Nullable<int> _YEAR;
		
		private System.Nullable<int> _COUNT;
		
		public QUERY_IIResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYID", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> COUNTRYID
		{
			get
			{
				return this._COUNTRYID;
			}
			set
			{
				if ((this._COUNTRYID != value))
				{
					this._COUNTRYID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRYNAME", DbType="VarChar(50)")]
		public string COUNTRYNAME
		{
			get
			{
				return this._COUNTRYNAME;
			}
			set
			{
				if ((this._COUNTRYNAME != value))
				{
					this._COUNTRYNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEAR", DbType="Int")]
		public System.Nullable<int> YEAR
		{
			get
			{
				return this._YEAR;
			}
			set
			{
				if ((this._YEAR != value))
				{
					this._YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNT", DbType="Int")]
		public System.Nullable<int> COUNT
		{
			get
			{
				return this._COUNT;
			}
			set
			{
				if ((this._COUNT != value))
				{
					this._COUNT = value;
				}
			}
		}
	}
	
	public partial class MAX_DATESResult
	{
		
		private System.Nullable<int> _maxi;
		
		private System.Nullable<int> _mini;
		
		public MAX_DATESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maxi", DbType="Int")]
		public System.Nullable<int> maxi
		{
			get
			{
				return this._maxi;
			}
			set
			{
				if ((this._maxi != value))
				{
					this._maxi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mini", DbType="Int")]
		public System.Nullable<int> mini
		{
			get
			{
				return this._mini;
			}
			set
			{
				if ((this._mini != value))
				{
					this._mini = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
