create table PERSON
(
	IDENTIFICATION NUMERIC(10) CONSTRAINT PERSON_PK PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	BIRTH_COUNTRY NUMERIC(10) NOT NULL CONSTRAINT BIRTH_PK REFERENCES COUNTRY(COUNTRYID),
	RESIDENCE_COUNTRY NUMERIC(10) NOT NULL CONSTRAINT RESIDENCE_PK REFERENCES COUNTRY(COUNTRYID),
	BIRTH_DATE DATE NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	FILEID uniqueidentifier ROWGUIDCOL  NOT NULL constraint PERSON_UNQ UNIQUE,
	PHOTO VARBINARY(MAX) NULL,
	VIDEO VARCHAR(300) NOT NULL
)
ALTER TABLE [dbo].PERSON ADD  CONSTRAINT [DF_PERSON_FILEID]  DEFAULT (newid()) FOR [FILEID]
GO
