//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestFS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.SolicitudSoap")]
    public interface SolicitudSoap {
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.FindCountryResponse FindCountry(TestFS.ServiceReference1.FindCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.FindCountryResponse> FindCountryAsync(TestFS.ServiceReference1.FindCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.clCountry[] GetCountries(object txn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.clCountry[]> GetCountriesAsync(object txn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCountries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        bool AddCountries(TestFS.ServiceReference1.clCountry[] countries);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AddCountriesAsync(TestFS.ServiceReference1.clCountry[] countries);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.AddCountryResponse AddCountry(TestFS.ServiceReference1.AddCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.AddCountryResponse> AddCountryAsync(TestFS.ServiceReference1.AddCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.DbTransaction test(TestFS.ServiceReference1.DbTransaction txn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.DbTransaction> testAsync(TestFS.ServiceReference1.DbTransaction txn);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountiesAt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.GetCountiesAtResponse GetCountiesAt(TestFS.ServiceReference1.GetCountiesAtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountiesAt", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.GetCountiesAtResponse> GetCountiesAtAsync(TestFS.ServiceReference1.GetCountiesAtRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.UpdateCountryResponse UpdateCountry(TestFS.ServiceReference1.UpdateCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.UpdateCountryResponse> UpdateCountryAsync(TestFS.ServiceReference1.UpdateCountryRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.deleteCountryResponse deleteCountry(TestFS.ServiceReference1.deleteCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.deleteCountryResponse> deleteCountryAsync(TestFS.ServiceReference1.deleteCountryRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.FindPersonResponse FindPerson(TestFS.ServiceReference1.FindPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.FindPersonResponse> FindPersonAsync(TestFS.ServiceReference1.FindPersonRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.AddPersonResponse AddPerson(TestFS.ServiceReference1.AddPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.AddPersonResponse> AddPersonAsync(TestFS.ServiceReference1.AddPersonRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPeopleAt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.GetPeopleAtResponse GetPeopleAt(TestFS.ServiceReference1.GetPeopleAtRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPeopleAt", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.GetPeopleAtResponse> GetPeopleAtAsync(TestFS.ServiceReference1.GetPeopleAtRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.UpdatePersonResponse UpdatePerson(TestFS.ServiceReference1.UpdatePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePerson", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.UpdatePersonResponse> UpdatePersonAsync(TestFS.ServiceReference1.UpdatePersonRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deletePerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.deletePersonResponse deletePerson(TestFS.ServiceReference1.deletePersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deletePerson", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.deletePersonResponse> deletePersonAsync(TestFS.ServiceReference1.deletePersonRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaisesLista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.GetPaisesListaResponse GetPaisesLista(TestFS.ServiceReference1.GetPaisesListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPaisesLista", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.GetPaisesListaResponse> GetPaisesListaAsync(TestFS.ServiceReference1.GetPaisesListaRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RollBack", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.RollBackResponse RollBack(TestFS.ServiceReference1.RollBackRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RollBack", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.RollBackResponse> RollBackAsync(TestFS.ServiceReference1.RollBackRequest request);
        
        // CODEGEN: Parameter 'tran' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Commit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.CommitResponse Commit(TestFS.ServiceReference1.CommitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Commit", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.CommitResponse> CommitAsync(TestFS.ServiceReference1.CommitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_COUNTRIES_INFO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.clCountry[] GET_COUNTRIES_INFO(long page, long size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GET_COUNTRIES_INFO", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.clCountry[]> GET_COUNTRIES_INFOAsync(long page, long size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PEOPLE_YEAR_COUNTRY", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.clCountry[] PEOPLE_YEAR_COUNTRY(decimal id, long page, long size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PEOPLE_YEAR_COUNTRY", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.clCountry[]> PEOPLE_YEAR_COUNTRYAsync(decimal id, long page, long size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PEOPLE_YEAR_ALLCOUNTRIES", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.clCountry[] PEOPLE_YEAR_ALLCOUNTRIES(long page, long size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PEOPLE_YEAR_ALLCOUNTRIES", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.clCountry[]> PEOPLE_YEAR_ALLCOUNTRIESAsync(long page, long size);
        
        // CODEGEN: Parameter 'get_page_countryResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_page_country", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.get_page_countryResponse get_page_country(TestFS.ServiceReference1.get_page_countryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_page_country", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.get_page_countryResponse> get_page_countryAsync(TestFS.ServiceReference1.get_page_countryRequest request);
        
        // CODEGEN: Parameter 'get_page_personResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_page_person", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.get_page_personResponse get_page_person(TestFS.ServiceReference1.get_page_personRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_page_person", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.get_page_personResponse> get_page_personAsync(TestFS.ServiceReference1.get_page_personRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Generate_People", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        bool Generate_People(decimal countries, decimal population);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Generate_People", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Generate_PeopleAsync(decimal countries, decimal population);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/query_II", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        TestFS.ServiceReference1.ResultList query_II();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/query_II", ReplyAction="*")]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.ResultList> query_IIAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clCountry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal cOUNTRYIDField;
        
        private string cOUNTRYNAMEField;
        
        private decimal aREAField;
        
        private decimal pOPULATIONField;
        
        private System.Guid fILEIDField;
        
        private byte[] fLAGField;
        
        private byte[] aNTHEMField;
        
        private System.Nullable<decimal> pRESIDENTField;
        
        private string fLAGB64Field;
        
        private string aNTHEMB64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal COUNTRYID {
            get {
                return this.cOUNTRYIDField;
            }
            set {
                this.cOUNTRYIDField = value;
                this.RaisePropertyChanged("COUNTRYID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string COUNTRYNAME {
            get {
                return this.cOUNTRYNAMEField;
            }
            set {
                this.cOUNTRYNAMEField = value;
                this.RaisePropertyChanged("COUNTRYNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal AREA {
            get {
                return this.aREAField;
            }
            set {
                this.aREAField = value;
                this.RaisePropertyChanged("AREA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal POPULATION {
            get {
                return this.pOPULATIONField;
            }
            set {
                this.pOPULATIONField = value;
                this.RaisePropertyChanged("POPULATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Guid FILEID {
            get {
                return this.fILEIDField;
            }
            set {
                this.fILEIDField = value;
                this.RaisePropertyChanged("FILEID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] FLAG {
            get {
                return this.fLAGField;
            }
            set {
                this.fLAGField = value;
                this.RaisePropertyChanged("FLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] ANTHEM {
            get {
                return this.aNTHEMField;
            }
            set {
                this.aNTHEMField = value;
                this.RaisePropertyChanged("ANTHEM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> PRESIDENT {
            get {
                return this.pRESIDENTField;
            }
            set {
                this.pRESIDENTField = value;
                this.RaisePropertyChanged("PRESIDENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FLAGB64 {
            get {
                return this.fLAGB64Field;
            }
            set {
                this.fLAGB64Field = value;
                this.RaisePropertyChanged("FLAGB64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ANTHEMB64 {
            get {
                return this.aNTHEMB64Field;
            }
            set {
                this.aNTHEMB64Field = value;
                this.RaisePropertyChanged("ANTHEMB64");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> countField;
        
        private string countrynameField;
        
        private System.Nullable<decimal> countryidField;
        
        private System.Nullable<int> yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string countryname {
            get {
                return this.countrynameField;
            }
            set {
                this.countrynameField = value;
                this.RaisePropertyChanged("countryname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> countryid {
            get {
                return this.countryidField;
            }
            set {
                this.countryidField = value;
                this.RaisePropertyChanged("countryid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Result[] listField;
        
        private System.Nullable<int> maxField;
        
        private System.Nullable<int> minField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Result[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("list");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
                this.RaisePropertyChanged("max");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
                this.RaisePropertyChanged("min");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clPerson : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal iDENTIFICATIONField;
        
        private string nAMEField;
        
        private string bIRTH_COUNTRYField;
        
        private string rESIDENCE_COUNTRYField;
        
        private decimal bIRTH_COUNTRY_IDField;
        
        private decimal rESIDENCE_COUNTRY_IDField;
        
        private System.DateTime bIRTH_DATEField;
        
        private string eMAILField;
        
        private byte[] pHOTOField;
        
        private string pHOTOB64Field;
        
        private string vIDEOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal IDENTIFICATION {
            get {
                return this.iDENTIFICATIONField;
            }
            set {
                this.iDENTIFICATIONField = value;
                this.RaisePropertyChanged("IDENTIFICATION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BIRTH_COUNTRY {
            get {
                return this.bIRTH_COUNTRYField;
            }
            set {
                this.bIRTH_COUNTRYField = value;
                this.RaisePropertyChanged("BIRTH_COUNTRY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RESIDENCE_COUNTRY {
            get {
                return this.rESIDENCE_COUNTRYField;
            }
            set {
                this.rESIDENCE_COUNTRYField = value;
                this.RaisePropertyChanged("RESIDENCE_COUNTRY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal BIRTH_COUNTRY_ID {
            get {
                return this.bIRTH_COUNTRY_IDField;
            }
            set {
                this.bIRTH_COUNTRY_IDField = value;
                this.RaisePropertyChanged("BIRTH_COUNTRY_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal RESIDENCE_COUNTRY_ID {
            get {
                return this.rESIDENCE_COUNTRY_IDField;
            }
            set {
                this.rESIDENCE_COUNTRY_IDField = value;
                this.RaisePropertyChanged("RESIDENCE_COUNTRY_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime BIRTH_DATE {
            get {
                return this.bIRTH_DATEField;
            }
            set {
                this.bIRTH_DATEField = value;
                this.RaisePropertyChanged("BIRTH_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
                this.RaisePropertyChanged("EMAIL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=8)]
        public byte[] PHOTO {
            get {
                return this.pHOTOField;
            }
            set {
                this.pHOTOField = value;
                this.RaisePropertyChanged("PHOTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PHOTOB64 {
            get {
                return this.pHOTOB64Field;
            }
            set {
                this.pHOTOB64Field = value;
                this.RaisePropertyChanged("PHOTOB64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string VIDEO {
            get {
                return this.vIDEOField;
            }
            set {
                this.vIDEOField = value;
                this.RaisePropertyChanged("VIDEO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DbTransaction))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2053.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class DbTransaction : MarshalByRefObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCountry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public FindCountryRequest() {
        }
        
        public FindCountryRequest(decimal id, System.Nullable<int> tran) {
            this.id = id;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindCountryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestFS.ServiceReference1.clCountry FindCountryResult;
        
        public FindCountryResponse() {
        }
        
        public FindCountryResponse(TestFS.ServiceReference1.clCountry FindCountryResult) {
            this.FindCountryResult = FindCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCountry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestFS.ServiceReference1.clCountry country;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public AddCountryRequest() {
        }
        
        public AddCountryRequest(TestFS.ServiceReference1.clCountry country, System.Nullable<int> tran) {
            this.country = country;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddCountryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int AddCountryResult;
        
        public AddCountryResponse() {
        }
        
        public AddCountryResponse(int AddCountryResult) {
            this.AddCountryResult = AddCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCountiesAt", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCountiesAtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public GetCountiesAtRequest() {
        }
        
        public GetCountiesAtRequest(decimal page, System.Nullable<int> tran) {
            this.page = page;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCountiesAtResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCountiesAtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestFS.ServiceReference1.clCountry[] GetCountiesAtResult;
        
        public GetCountiesAtResponse() {
        }
        
        public GetCountiesAtResponse(TestFS.ServiceReference1.clCountry[] GetCountiesAtResult) {
            this.GetCountiesAtResult = GetCountiesAtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCountry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestFS.ServiceReference1.clCountry country;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal old_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public UpdateCountryRequest() {
        }
        
        public UpdateCountryRequest(TestFS.ServiceReference1.clCountry country, decimal old_id, System.Nullable<int> tran) {
            this.country = country;
            this.old_id = old_id;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCountryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UpdateCountryResult;
        
        public UpdateCountryResponse() {
        }
        
        public UpdateCountryResponse(int UpdateCountryResult) {
            this.UpdateCountryResult = UpdateCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCountry", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public deleteCountryRequest() {
        }
        
        public deleteCountryRequest(decimal id, System.Nullable<int> tran) {
            this.id = id;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteCountryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int deleteCountryResult;
        
        public deleteCountryResponse() {
        }
        
        public deleteCountryResponse(int deleteCountryResult) {
            this.deleteCountryResult = deleteCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindPerson", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public FindPersonRequest() {
        }
        
        public FindPersonRequest(decimal id, System.Nullable<int> tran) {
            this.id = id;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindPersonResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FindPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestFS.ServiceReference1.clPerson FindPersonResult;
        
        public FindPersonResponse() {
        }
        
        public FindPersonResponse(TestFS.ServiceReference1.clPerson FindPersonResult) {
            this.FindPersonResult = FindPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPerson", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestFS.ServiceReference1.clPerson person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public AddPersonRequest() {
        }
        
        public AddPersonRequest(TestFS.ServiceReference1.clPerson person, System.Nullable<int> tran) {
            this.person = person;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddPersonResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int AddPersonResult;
        
        public AddPersonResponse() {
        }
        
        public AddPersonResponse(int AddPersonResult) {
            this.AddPersonResult = AddPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPeopleAt", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPeopleAtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal page_size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public GetPeopleAtRequest() {
        }
        
        public GetPeopleAtRequest(decimal page, decimal page_size, System.Nullable<int> tran) {
            this.page = page;
            this.page_size = page_size;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPeopleAtResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPeopleAtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestFS.ServiceReference1.clPerson[] GetPeopleAtResult;
        
        public GetPeopleAtResponse() {
        }
        
        public GetPeopleAtResponse(TestFS.ServiceReference1.clPerson[] GetPeopleAtResult) {
            this.GetPeopleAtResult = GetPeopleAtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePerson", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestFS.ServiceReference1.clPerson person;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal old_id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public UpdatePersonRequest() {
        }
        
        public UpdatePersonRequest(TestFS.ServiceReference1.clPerson person, decimal old_id, System.Nullable<int> tran) {
            this.person = person;
            this.old_id = old_id;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePersonResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdatePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int UpdatePersonResult;
        
        public UpdatePersonResponse() {
        }
        
        public UpdatePersonResponse(int UpdatePersonResult) {
            this.UpdatePersonResult = UpdatePersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deletePerson", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deletePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public decimal id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public deletePersonRequest() {
        }
        
        public deletePersonRequest(decimal id, System.Nullable<int> tran) {
            this.id = id;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deletePersonResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deletePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int deletePersonResult;
        
        public deletePersonResponse() {
        }
        
        public deletePersonResponse(int deletePersonResult) {
            this.deletePersonResult = deletePersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaisesLista", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaisesListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public GetPaisesListaRequest() {
        }
        
        public GetPaisesListaRequest(System.Nullable<int> tran) {
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPaisesListaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPaisesListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TestFS.ServiceReference1.clCountry[] GetPaisesListaResult;
        
        public GetPaisesListaResponse() {
        }
        
        public GetPaisesListaResponse(TestFS.ServiceReference1.clCountry[] GetPaisesListaResult) {
            this.GetPaisesListaResult = GetPaisesListaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RollBack", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RollBackRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public RollBackRequest() {
        }
        
        public RollBackRequest(System.Nullable<int> tran) {
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RollBackResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RollBackResponse {
        
        public RollBackResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Commit", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CommitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public CommitRequest() {
        }
        
        public CommitRequest(System.Nullable<int> tran) {
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CommitResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CommitResponse {
        
        public CommitResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_page_country", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_page_countryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public get_page_countryRequest() {
        }
        
        public get_page_countryRequest(int page, System.Nullable<int> tran) {
            this.page = page;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_page_countryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_page_countryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> get_page_countryResult;
        
        public get_page_countryResponse() {
        }
        
        public get_page_countryResponse(System.Nullable<int> get_page_countryResult) {
            this.get_page_countryResult = get_page_countryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_page_person", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_page_personRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> tran;
        
        public get_page_personRequest() {
        }
        
        public get_page_personRequest(int page, System.Nullable<int> tran) {
            this.page = page;
            this.tran = tran;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_page_personResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class get_page_personResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> get_page_personResult;
        
        public get_page_personResponse() {
        }
        
        public get_page_personResponse(System.Nullable<int> get_page_personResult) {
            this.get_page_personResult = get_page_personResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SolicitudSoapChannel : TestFS.ServiceReference1.SolicitudSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SolicitudSoapClient : System.ServiceModel.ClientBase<TestFS.ServiceReference1.SolicitudSoap>, TestFS.ServiceReference1.SolicitudSoap {
        
        public SolicitudSoapClient() {
        }
        
        public SolicitudSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SolicitudSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SolicitudSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.FindCountryResponse TestFS.ServiceReference1.SolicitudSoap.FindCountry(TestFS.ServiceReference1.FindCountryRequest request) {
            return base.Channel.FindCountry(request);
        }
        
        public TestFS.ServiceReference1.clCountry FindCountry(decimal id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.FindCountryRequest inValue = new TestFS.ServiceReference1.FindCountryRequest();
            inValue.id = id;
            inValue.tran = tran;
            TestFS.ServiceReference1.FindCountryResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).FindCountry(inValue);
            return retVal.FindCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.FindCountryResponse> TestFS.ServiceReference1.SolicitudSoap.FindCountryAsync(TestFS.ServiceReference1.FindCountryRequest request) {
            return base.Channel.FindCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.FindCountryResponse> FindCountryAsync(decimal id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.FindCountryRequest inValue = new TestFS.ServiceReference1.FindCountryRequest();
            inValue.id = id;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).FindCountryAsync(inValue);
        }
        
        public TestFS.ServiceReference1.clCountry[] GetCountries(object txn) {
            return base.Channel.GetCountries(txn);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.clCountry[]> GetCountriesAsync(object txn) {
            return base.Channel.GetCountriesAsync(txn);
        }
        
        public bool AddCountries(TestFS.ServiceReference1.clCountry[] countries) {
            return base.Channel.AddCountries(countries);
        }
        
        public System.Threading.Tasks.Task<bool> AddCountriesAsync(TestFS.ServiceReference1.clCountry[] countries) {
            return base.Channel.AddCountriesAsync(countries);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.AddCountryResponse TestFS.ServiceReference1.SolicitudSoap.AddCountry(TestFS.ServiceReference1.AddCountryRequest request) {
            return base.Channel.AddCountry(request);
        }
        
        public int AddCountry(TestFS.ServiceReference1.clCountry country, System.Nullable<int> tran) {
            TestFS.ServiceReference1.AddCountryRequest inValue = new TestFS.ServiceReference1.AddCountryRequest();
            inValue.country = country;
            inValue.tran = tran;
            TestFS.ServiceReference1.AddCountryResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).AddCountry(inValue);
            return retVal.AddCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.AddCountryResponse> TestFS.ServiceReference1.SolicitudSoap.AddCountryAsync(TestFS.ServiceReference1.AddCountryRequest request) {
            return base.Channel.AddCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.AddCountryResponse> AddCountryAsync(TestFS.ServiceReference1.clCountry country, System.Nullable<int> tran) {
            TestFS.ServiceReference1.AddCountryRequest inValue = new TestFS.ServiceReference1.AddCountryRequest();
            inValue.country = country;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).AddCountryAsync(inValue);
        }
        
        public TestFS.ServiceReference1.DbTransaction test(TestFS.ServiceReference1.DbTransaction txn) {
            return base.Channel.test(txn);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.DbTransaction> testAsync(TestFS.ServiceReference1.DbTransaction txn) {
            return base.Channel.testAsync(txn);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.GetCountiesAtResponse TestFS.ServiceReference1.SolicitudSoap.GetCountiesAt(TestFS.ServiceReference1.GetCountiesAtRequest request) {
            return base.Channel.GetCountiesAt(request);
        }
        
        public TestFS.ServiceReference1.clCountry[] GetCountiesAt(decimal page, System.Nullable<int> tran) {
            TestFS.ServiceReference1.GetCountiesAtRequest inValue = new TestFS.ServiceReference1.GetCountiesAtRequest();
            inValue.page = page;
            inValue.tran = tran;
            TestFS.ServiceReference1.GetCountiesAtResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).GetCountiesAt(inValue);
            return retVal.GetCountiesAtResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.GetCountiesAtResponse> TestFS.ServiceReference1.SolicitudSoap.GetCountiesAtAsync(TestFS.ServiceReference1.GetCountiesAtRequest request) {
            return base.Channel.GetCountiesAtAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.GetCountiesAtResponse> GetCountiesAtAsync(decimal page, System.Nullable<int> tran) {
            TestFS.ServiceReference1.GetCountiesAtRequest inValue = new TestFS.ServiceReference1.GetCountiesAtRequest();
            inValue.page = page;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).GetCountiesAtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.UpdateCountryResponse TestFS.ServiceReference1.SolicitudSoap.UpdateCountry(TestFS.ServiceReference1.UpdateCountryRequest request) {
            return base.Channel.UpdateCountry(request);
        }
        
        public int UpdateCountry(TestFS.ServiceReference1.clCountry country, decimal old_id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.UpdateCountryRequest inValue = new TestFS.ServiceReference1.UpdateCountryRequest();
            inValue.country = country;
            inValue.old_id = old_id;
            inValue.tran = tran;
            TestFS.ServiceReference1.UpdateCountryResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).UpdateCountry(inValue);
            return retVal.UpdateCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.UpdateCountryResponse> TestFS.ServiceReference1.SolicitudSoap.UpdateCountryAsync(TestFS.ServiceReference1.UpdateCountryRequest request) {
            return base.Channel.UpdateCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.UpdateCountryResponse> UpdateCountryAsync(TestFS.ServiceReference1.clCountry country, decimal old_id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.UpdateCountryRequest inValue = new TestFS.ServiceReference1.UpdateCountryRequest();
            inValue.country = country;
            inValue.old_id = old_id;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).UpdateCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.deleteCountryResponse TestFS.ServiceReference1.SolicitudSoap.deleteCountry(TestFS.ServiceReference1.deleteCountryRequest request) {
            return base.Channel.deleteCountry(request);
        }
        
        public int deleteCountry(decimal id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.deleteCountryRequest inValue = new TestFS.ServiceReference1.deleteCountryRequest();
            inValue.id = id;
            inValue.tran = tran;
            TestFS.ServiceReference1.deleteCountryResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).deleteCountry(inValue);
            return retVal.deleteCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.deleteCountryResponse> TestFS.ServiceReference1.SolicitudSoap.deleteCountryAsync(TestFS.ServiceReference1.deleteCountryRequest request) {
            return base.Channel.deleteCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.deleteCountryResponse> deleteCountryAsync(decimal id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.deleteCountryRequest inValue = new TestFS.ServiceReference1.deleteCountryRequest();
            inValue.id = id;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).deleteCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.FindPersonResponse TestFS.ServiceReference1.SolicitudSoap.FindPerson(TestFS.ServiceReference1.FindPersonRequest request) {
            return base.Channel.FindPerson(request);
        }
        
        public TestFS.ServiceReference1.clPerson FindPerson(decimal id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.FindPersonRequest inValue = new TestFS.ServiceReference1.FindPersonRequest();
            inValue.id = id;
            inValue.tran = tran;
            TestFS.ServiceReference1.FindPersonResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).FindPerson(inValue);
            return retVal.FindPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.FindPersonResponse> TestFS.ServiceReference1.SolicitudSoap.FindPersonAsync(TestFS.ServiceReference1.FindPersonRequest request) {
            return base.Channel.FindPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.FindPersonResponse> FindPersonAsync(decimal id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.FindPersonRequest inValue = new TestFS.ServiceReference1.FindPersonRequest();
            inValue.id = id;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).FindPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.AddPersonResponse TestFS.ServiceReference1.SolicitudSoap.AddPerson(TestFS.ServiceReference1.AddPersonRequest request) {
            return base.Channel.AddPerson(request);
        }
        
        public int AddPerson(TestFS.ServiceReference1.clPerson person, System.Nullable<int> tran) {
            TestFS.ServiceReference1.AddPersonRequest inValue = new TestFS.ServiceReference1.AddPersonRequest();
            inValue.person = person;
            inValue.tran = tran;
            TestFS.ServiceReference1.AddPersonResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).AddPerson(inValue);
            return retVal.AddPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.AddPersonResponse> TestFS.ServiceReference1.SolicitudSoap.AddPersonAsync(TestFS.ServiceReference1.AddPersonRequest request) {
            return base.Channel.AddPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.AddPersonResponse> AddPersonAsync(TestFS.ServiceReference1.clPerson person, System.Nullable<int> tran) {
            TestFS.ServiceReference1.AddPersonRequest inValue = new TestFS.ServiceReference1.AddPersonRequest();
            inValue.person = person;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).AddPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.GetPeopleAtResponse TestFS.ServiceReference1.SolicitudSoap.GetPeopleAt(TestFS.ServiceReference1.GetPeopleAtRequest request) {
            return base.Channel.GetPeopleAt(request);
        }
        
        public TestFS.ServiceReference1.clPerson[] GetPeopleAt(decimal page, decimal page_size, System.Nullable<int> tran) {
            TestFS.ServiceReference1.GetPeopleAtRequest inValue = new TestFS.ServiceReference1.GetPeopleAtRequest();
            inValue.page = page;
            inValue.page_size = page_size;
            inValue.tran = tran;
            TestFS.ServiceReference1.GetPeopleAtResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).GetPeopleAt(inValue);
            return retVal.GetPeopleAtResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.GetPeopleAtResponse> TestFS.ServiceReference1.SolicitudSoap.GetPeopleAtAsync(TestFS.ServiceReference1.GetPeopleAtRequest request) {
            return base.Channel.GetPeopleAtAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.GetPeopleAtResponse> GetPeopleAtAsync(decimal page, decimal page_size, System.Nullable<int> tran) {
            TestFS.ServiceReference1.GetPeopleAtRequest inValue = new TestFS.ServiceReference1.GetPeopleAtRequest();
            inValue.page = page;
            inValue.page_size = page_size;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).GetPeopleAtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.UpdatePersonResponse TestFS.ServiceReference1.SolicitudSoap.UpdatePerson(TestFS.ServiceReference1.UpdatePersonRequest request) {
            return base.Channel.UpdatePerson(request);
        }
        
        public int UpdatePerson(TestFS.ServiceReference1.clPerson person, decimal old_id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.UpdatePersonRequest inValue = new TestFS.ServiceReference1.UpdatePersonRequest();
            inValue.person = person;
            inValue.old_id = old_id;
            inValue.tran = tran;
            TestFS.ServiceReference1.UpdatePersonResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).UpdatePerson(inValue);
            return retVal.UpdatePersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.UpdatePersonResponse> TestFS.ServiceReference1.SolicitudSoap.UpdatePersonAsync(TestFS.ServiceReference1.UpdatePersonRequest request) {
            return base.Channel.UpdatePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.UpdatePersonResponse> UpdatePersonAsync(TestFS.ServiceReference1.clPerson person, decimal old_id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.UpdatePersonRequest inValue = new TestFS.ServiceReference1.UpdatePersonRequest();
            inValue.person = person;
            inValue.old_id = old_id;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).UpdatePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.deletePersonResponse TestFS.ServiceReference1.SolicitudSoap.deletePerson(TestFS.ServiceReference1.deletePersonRequest request) {
            return base.Channel.deletePerson(request);
        }
        
        public int deletePerson(decimal id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.deletePersonRequest inValue = new TestFS.ServiceReference1.deletePersonRequest();
            inValue.id = id;
            inValue.tran = tran;
            TestFS.ServiceReference1.deletePersonResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).deletePerson(inValue);
            return retVal.deletePersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.deletePersonResponse> TestFS.ServiceReference1.SolicitudSoap.deletePersonAsync(TestFS.ServiceReference1.deletePersonRequest request) {
            return base.Channel.deletePersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.deletePersonResponse> deletePersonAsync(decimal id, System.Nullable<int> tran) {
            TestFS.ServiceReference1.deletePersonRequest inValue = new TestFS.ServiceReference1.deletePersonRequest();
            inValue.id = id;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).deletePersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.GetPaisesListaResponse TestFS.ServiceReference1.SolicitudSoap.GetPaisesLista(TestFS.ServiceReference1.GetPaisesListaRequest request) {
            return base.Channel.GetPaisesLista(request);
        }
        
        public TestFS.ServiceReference1.clCountry[] GetPaisesLista(System.Nullable<int> tran) {
            TestFS.ServiceReference1.GetPaisesListaRequest inValue = new TestFS.ServiceReference1.GetPaisesListaRequest();
            inValue.tran = tran;
            TestFS.ServiceReference1.GetPaisesListaResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).GetPaisesLista(inValue);
            return retVal.GetPaisesListaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.GetPaisesListaResponse> TestFS.ServiceReference1.SolicitudSoap.GetPaisesListaAsync(TestFS.ServiceReference1.GetPaisesListaRequest request) {
            return base.Channel.GetPaisesListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.GetPaisesListaResponse> GetPaisesListaAsync(System.Nullable<int> tran) {
            TestFS.ServiceReference1.GetPaisesListaRequest inValue = new TestFS.ServiceReference1.GetPaisesListaRequest();
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).GetPaisesListaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.RollBackResponse TestFS.ServiceReference1.SolicitudSoap.RollBack(TestFS.ServiceReference1.RollBackRequest request) {
            return base.Channel.RollBack(request);
        }
        
        public void RollBack(System.Nullable<int> tran) {
            TestFS.ServiceReference1.RollBackRequest inValue = new TestFS.ServiceReference1.RollBackRequest();
            inValue.tran = tran;
            TestFS.ServiceReference1.RollBackResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).RollBack(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.RollBackResponse> TestFS.ServiceReference1.SolicitudSoap.RollBackAsync(TestFS.ServiceReference1.RollBackRequest request) {
            return base.Channel.RollBackAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.RollBackResponse> RollBackAsync(System.Nullable<int> tran) {
            TestFS.ServiceReference1.RollBackRequest inValue = new TestFS.ServiceReference1.RollBackRequest();
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).RollBackAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.CommitResponse TestFS.ServiceReference1.SolicitudSoap.Commit(TestFS.ServiceReference1.CommitRequest request) {
            return base.Channel.Commit(request);
        }
        
        public void Commit(System.Nullable<int> tran) {
            TestFS.ServiceReference1.CommitRequest inValue = new TestFS.ServiceReference1.CommitRequest();
            inValue.tran = tran;
            TestFS.ServiceReference1.CommitResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).Commit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.CommitResponse> TestFS.ServiceReference1.SolicitudSoap.CommitAsync(TestFS.ServiceReference1.CommitRequest request) {
            return base.Channel.CommitAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.CommitResponse> CommitAsync(System.Nullable<int> tran) {
            TestFS.ServiceReference1.CommitRequest inValue = new TestFS.ServiceReference1.CommitRequest();
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).CommitAsync(inValue);
        }
        
        public TestFS.ServiceReference1.clCountry[] GET_COUNTRIES_INFO(long page, long size) {
            return base.Channel.GET_COUNTRIES_INFO(page, size);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.clCountry[]> GET_COUNTRIES_INFOAsync(long page, long size) {
            return base.Channel.GET_COUNTRIES_INFOAsync(page, size);
        }
        
        public TestFS.ServiceReference1.clCountry[] PEOPLE_YEAR_COUNTRY(decimal id, long page, long size) {
            return base.Channel.PEOPLE_YEAR_COUNTRY(id, page, size);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.clCountry[]> PEOPLE_YEAR_COUNTRYAsync(decimal id, long page, long size) {
            return base.Channel.PEOPLE_YEAR_COUNTRYAsync(id, page, size);
        }
        
        public TestFS.ServiceReference1.clCountry[] PEOPLE_YEAR_ALLCOUNTRIES(long page, long size) {
            return base.Channel.PEOPLE_YEAR_ALLCOUNTRIES(page, size);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.clCountry[]> PEOPLE_YEAR_ALLCOUNTRIESAsync(long page, long size) {
            return base.Channel.PEOPLE_YEAR_ALLCOUNTRIESAsync(page, size);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.get_page_countryResponse TestFS.ServiceReference1.SolicitudSoap.get_page_country(TestFS.ServiceReference1.get_page_countryRequest request) {
            return base.Channel.get_page_country(request);
        }
        
        public System.Nullable<int> get_page_country(int page, System.Nullable<int> tran) {
            TestFS.ServiceReference1.get_page_countryRequest inValue = new TestFS.ServiceReference1.get_page_countryRequest();
            inValue.page = page;
            inValue.tran = tran;
            TestFS.ServiceReference1.get_page_countryResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).get_page_country(inValue);
            return retVal.get_page_countryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.get_page_countryResponse> TestFS.ServiceReference1.SolicitudSoap.get_page_countryAsync(TestFS.ServiceReference1.get_page_countryRequest request) {
            return base.Channel.get_page_countryAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.get_page_countryResponse> get_page_countryAsync(int page, System.Nullable<int> tran) {
            TestFS.ServiceReference1.get_page_countryRequest inValue = new TestFS.ServiceReference1.get_page_countryRequest();
            inValue.page = page;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).get_page_countryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestFS.ServiceReference1.get_page_personResponse TestFS.ServiceReference1.SolicitudSoap.get_page_person(TestFS.ServiceReference1.get_page_personRequest request) {
            return base.Channel.get_page_person(request);
        }
        
        public System.Nullable<int> get_page_person(int page, System.Nullable<int> tran) {
            TestFS.ServiceReference1.get_page_personRequest inValue = new TestFS.ServiceReference1.get_page_personRequest();
            inValue.page = page;
            inValue.tran = tran;
            TestFS.ServiceReference1.get_page_personResponse retVal = ((TestFS.ServiceReference1.SolicitudSoap)(this)).get_page_person(inValue);
            return retVal.get_page_personResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestFS.ServiceReference1.get_page_personResponse> TestFS.ServiceReference1.SolicitudSoap.get_page_personAsync(TestFS.ServiceReference1.get_page_personRequest request) {
            return base.Channel.get_page_personAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.get_page_personResponse> get_page_personAsync(int page, System.Nullable<int> tran) {
            TestFS.ServiceReference1.get_page_personRequest inValue = new TestFS.ServiceReference1.get_page_personRequest();
            inValue.page = page;
            inValue.tran = tran;
            return ((TestFS.ServiceReference1.SolicitudSoap)(this)).get_page_personAsync(inValue);
        }
        
        public bool Generate_People(decimal countries, decimal population) {
            return base.Channel.Generate_People(countries, population);
        }
        
        public System.Threading.Tasks.Task<bool> Generate_PeopleAsync(decimal countries, decimal population) {
            return base.Channel.Generate_PeopleAsync(countries, population);
        }
        
        public TestFS.ServiceReference1.ResultList query_II() {
            return base.Channel.query_II();
        }
        
        public System.Threading.Tasks.Task<TestFS.ServiceReference1.ResultList> query_IIAsync() {
            return base.Channel.query_IIAsync();
        }
    }
}
